# Generated by Django 4.1.9 on 2023-07-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_game_info_game_moves_alter_game_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
