# Generated by Django 4.1.9 on 2023-07-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_game_to_move'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GamePuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('solution', models.TextField()),
                ('info', models.TextField()),
                ('to_move', models.CharField(default='white', max_length=5)),
            ],
        ),
    ]
